---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
- name: debian-7.6
- name: ubuntu-14.04
- name: centos-6.5
  # To run test-kitchen for OS X, create a box for 10.9, and add it to
  # vagrant. See for example,
  # https://github.com/timsutton/osx-vm-templates
  # https://github.com/opscode/bento/blob/master/packer/macosx-10.9.json
- name: macosx-10.9
  driver:
    box: chef/macosx-10.9

suites:
- name: debian
  run_list:
    - recipe[vagrant]
    - recipe[test]
  excludes:
    - centos-6.5
    - macosx-10.9
  attributes:
    vagrant:
      plugins:
        - vagrant-omnibus

- name: rhel
  run_list:
    - recipe[vagrant]
    - recipe[test]
  excludes:
    - ubuntu-14.04
    - debian-7.6
    - macosx-10.9
  attributes:
    vagrant:
      plugins:
        - vagrant-omnibus

- name: osx
  run_list:
    - recipe[vagrant]
    - recipe[test]
  excludes:
    - ubuntu-14.04
    - debian-7.6
    - centos-6.5
  attributes:
    vagrant:
      plugins:
        - vagrant-omnibus
